name: Build and Release JAR

on:
  release:
    types: [created]

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Upload JAR to GitHub Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: target/ProtocolSwitchingFileIO-1.0.0.jar # Adjust based on your JAR name
        asset_name: ProtocolSwitchingFileIO.jar
        asset_content_type: application/java-archive
